kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv    
  # namespace is not required
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage # Use the local storage class (cloud storage, NFS, etc.)
  hostPath:
    path: /mnt/data 